//
//  Assets.swift
//  Open Souq Assignment
//
//  Generated using SwiftGen, by O.Halligon — https://github.com/AliSoftware/SwiftGen
//  Copyright © 2015 Mamouneyya. All rights reserved.
//

import Foundation
import UIKit

// MARK: - Storyboards
// Automatically generated by swiftrsrc. Do not edit.

struct MainStoryboard {
    struct StoryboardIdentifiers {
    }
    struct ReuseIdentifiers {
        static let ApplicationCell = "ApplicationCell"
    }
    struct SegueIdentifiers {
        static let ToApplication = "ToApplication"
    }
}

// MARK: - Assets Catalog
// Automatically generated by swiftrsrc. Do not edit.

struct AssetsCatalog {
    static var ImagePlaceholder: UIImage { return UIImage(named: "image-placeholder")! }
}
